---
kind: pipeline
type: kubernetes
name: default

steps:
- name: build & push docker image
  image: plugins/docker
  when:
    event:
    - tag
  settings:
    username: dgrechka
    password:
      from_secret: dgrechka_ghcr_pat
    repo: ghcr.io/grechka-family/nextcloud
    registry: ghcr.io
    auto_tag: true
    force_tag: true